import { createApiClient as createCoreApiClient, type ApiClient } from '@nessie/client-core'

export type { ApiClient }

// Admin (Vite) resolves the API base URL from build-time env. This is the
// single web-specific seam; @nessie/client-core stays env-agnostic and has the
// base URL injected by the host (here).
export const getBaseUrl = (): string => {
  const configuredBaseUrl = import.meta.env?.VITE_API_BASE_URL?.trim()
  return configuredBaseUrl ? configuredBaseUrl.replace(/\/$/, '') : ''
}

export const createApiClient = (
  token: string | null,
  onUnauthorized?: () => Promise<string | null>,
): ApiClient =>
  createCoreApiClient({ baseUrl: getBaseUrl(), token, onUnauthorized })

// Re-export the shared API data-shape + schema types so existing
// `import { ... } from '../lib/api-client'` call sites keep working.
export type {
  AgentModelOption,
  AgentActivityResponse,
  AgentChild,
  AgentMessage,
  AgentRecord,
  AgentStatusResponse,
  AgentTriggerDeliveryRecord,
  AgentTriggerRecord,
  AuthProviderDescriptor,
  BootstrapModeResponse,
  BuildMeProjectHandoffIntent,
  BuildMeProjectHandoffRequest,
  CallParticipantRecord,
  CallRecord,
  ChannelMetadataRecord,
  ChannelRecord,
  CommsConnectionDetail,
  CommsConnectionListResponse,
  CommsConnectionStartResponse,
  CommsConnectionStatus,
  CommsConnectionSummary,
  CommsProvider,
  CommsResourceRecord,
  CommsResourcesPatchRequest,
  CommsResourceToggle,
  CommsSyncJobRecord,
  CommsSyncPhase,
  CommsSyncStatus,
  CreateFeedbackRequest,
  DeepSignalSignalAction,
  DeepSignalSignalActResponse,
  DeepSignalSignalKind,
  DeepSignalSignalRecord,
  DeepSignalSignalsResponse,
  DeepTestReviewDepth,
  DeepTestReviewHandoffRequest,
  DeepWaterResearchDepth,
  DeepWaterAgentAccessResponse,
  DeepWaterAgentAccessTarget,
  DeepWaterResearchLauncherPreset,
  DeepWaterResearchLaunchRequest,
  DeepWaterResearchRunRecord,
  ExecutorAccessChangeRequest,
  ExecutorAccessChangeResponse,
  ExecutorAccessViewResponse,
  ExecutorRecordResponse,
  FavoriteRecord,
  FavoriteTargetType,
  FeedbackRecord,
  IntegratedProductAuthMode,
  IntegratedProductCategory,
  IntegratedProductHealthStatus,
  IntegratedProductInstallState,
  IntegratedProductResponse,
  IntegrationPluginAvailability,
  IntegrationPluginInstallMode,
  IntegrationPluginManifest,
  IntegrationPluginPrivacyTier,
  IntegrationPluginSurfaceStatus,
  IntegrationUiCard,
  IntegrationUiCardAction,
  IntegrationUiCardField,
  IntegrationUiCardStatus,
  MeResponse,
  MessageReaction,
  MessageSearchResult,
  OrganizationSummary,
  PresenceEntry,
  PresenceListResponse,
  PresenceManualState,
  PresenceState,
  PersonalAssistantBootstrapResponse,
  PersonalAssistantConfigSummary,
  PersonalAssistantInstanceRecord,
  PersonalAssistantStateResponse,
  ProjectMemberRecord,
  ProjectRecord,
  ProductAccountLinkRecord,
  ProductAccountLinkStatus,
  ProductIntegrationRunStatus,
  ProductMcpInstallationRecord,
  ProductTeamEnablementAuthority,
  ProductTeamEnablementRecord,
  SetProductTeamEnablementRequest,
  SetDeepWaterAgentAccessRequest,
  SessionState,
  TeamRecord,
  ThreadMessageRecord,
  ThreadRecord,
  ToolCallEntry,
  ToolDescriptor,
  UserActiveStatus,
  UserRecord,
  UserStatusRecord,
  UserStatusRuleRecord,
  UserStatusRuleScope,
  UserStatusScheduleKind,
  UserStatusScheduleRecord,
  WorkflowInstallationRecord,
  WorkflowRunDetail,
  WorkflowRunRecord,
  WorkflowRunStatus,
  WorkflowStepRunRecord,
  WorkflowStepSamplesRecord,
  WorkflowStepRunStatus,
  WorkflowTemplateRecord,
} from '@nessie/client-core'
