services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: nessie-local-postgres
    environment:
      POSTGRES_DB: nessie
      POSTGRES_PASSWORD: nessie
      POSTGRES_USER: nessie
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nessie -d nessie"]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - "55432:5432"
    volumes:
      - ../../.nessie/docker/postgres:/var/lib/postgresql/data
