export const EXECUTOR_ERROR_CODES = {
  ACCESS_CHANGE_EXPIRED: 'EXECUTOR_ACCESS_CHANGE_EXPIRED',
  ACCESS_CHANGE_NOT_FOUND: 'EXECUTOR_ACCESS_CHANGE_NOT_FOUND',
  ACCESS_CHANGE_STALE: 'EXECUTOR_ACCESS_CHANGE_STALE',
  ENROLLMENT_EXPIRED: 'ENROLLMENT_EXPIRED',
  ENROLLMENT_PROOF_INVALID: 'ENROLLMENT_PROOF_INVALID',
  ENROLLMENT_USED: 'ENROLLMENT_USED',
  FINGERPRINT_NOT_CONFIRMED: 'FINGERPRINT_NOT_CONFIRMED',
  FRESH_VERIFICATION_REQUIRED: 'EXECUTOR_FRESH_VERIFICATION_REQUIRED',
  NOT_FOUND: 'EXECUTOR_NOT_FOUND',
  PRIVATE_FINAL_ADMIN_REQUIRED: 'EXECUTOR_PRIVATE_FINAL_ADMIN_REQUIRED',
  SCOPE_ENTITLEMENT_DENIED: 'SCOPE_ENTITLEMENT_DENIED',
  SCOPE_INVALID: 'EXECUTOR_SCOPE_INVALID',
  STATE_TRANSITION_INVALID: 'EXECUTOR_STATE_TRANSITION_INVALID',
} as const

export class ExecutorError extends Error {
  override readonly name = 'ExecutorError'

  constructor(
    public readonly code: (typeof EXECUTOR_ERROR_CODES)[keyof typeof EXECUTOR_ERROR_CODES],
    message: string,
  ) {
    super(message)
  }
}
