import assert from 'node:assert/strict'
import { mkdir } from 'node:fs/promises'
import { resolve } from 'node:path'
import { launchBrowser } from '../navigation/lib/browser.mjs'
import { REPO_ROOT } from '../navigation/lib/config.mjs'

const output = resolve(REPO_ROOT, 'e2e/screenshots/member-management')
const browser = await launchBrowser()
await mkdir(output, { recursive: true })
const calls = (page) => page.evaluate(() => window.memberManagementCalls)
const tab = async (page, label) => {
  const direct = page.getByRole('tab', { name: label, exact: true })
  if (await direct.isVisible()) await direct.click()
  else {
    await page.getByRole('button', { name: 'Member status', exact: true }).click()
    await page.getByRole('option', { name: label, exact: true }).click()
  }
}
try {
  for (const width of [1280, 390]) {
    const context = await browser.newContext({ viewport: { width, height: 844 }, hasTouch: width === 390 })
    // The only network the fixture can make is the auth provider's empty-session read.
    // Every roster mutation is an isolated, stateful API fixture, never a real invitation.
    await context.route('**/api/**', (route) => route.fulfill({ json: { data: {} } }))
    const page = await context.newPage()
    const errors = []
    page.on('pageerror', (error) => errors.push(error.message))
    const open = async (params = '') => {
      await page.goto(`http://localhost:5455/e2e/member-management/index.html${params}`)
      await page.getByRole('heading', { name: 'Members', exact: true }).waitFor()
    }
    const member = () => page.getByRole('button', { name: 'Open Jakub Rafaj', exact: true })
    const dialogClosed = () => page.getByRole('dialog').waitFor({ state: 'hidden' })
    await open()
    await member().click()
    await page.getByLabel('Role', { exact: true }).selectOption('admin')
    await page.screenshot({ path: resolve(output, `${width}-role-change.png`) })
    await page.getByRole('button', { name: 'Save changes', exact: true }).click()
    await dialogClosed()
    assert.ok((await calls(page)).some((call) => call.path.endsWith('/subject-jakub/role') && call.body.role === 'admin'))
    await member().click()
    assert.equal(await page.getByLabel('Role', { exact: true }).inputValue(), 'admin')
    await page.getByRole('button', { name: 'Deactivate in organization', exact: true }).click()
    await page.getByText('This suspends their access across the entire organization, including its other teams.').waitFor()
    await page.getByTestId('confirm-dialog-confirm').click()
    await dialogClosed()
    await tab(page, 'Deactivated users')
    await member().click()
    await page.getByRole('button', { name: 'Reactivate in organization', exact: true }).click()
    await page.getByTestId('confirm-dialog-confirm').click()
    await dialogClosed()
    await tab(page, 'Active users')
    await member().click()
    await page.getByRole('button', { name: 'Remove from team', exact: true }).click()
    await page.getByTestId('confirm-dialog-cancel').click()
    assert.equal((await calls(page)).some((call) => call.method === 'DELETE'), false)
    await page.getByRole('button', { name: 'Remove from team', exact: true }).click()
    await page.getByTestId('confirm-dialog-confirm').click()
    await dialogClosed()
    await page.getByText('No active users', { exact: true }).waitFor()

    for (const scope of ['team', 'organization']) {
      await open(`?scope=${scope}`)
      await page.getByRole('button', { name: 'Send invitation', exact: true }).click()
      assert.equal(await page.getByText('Set up automatic team access', { exact: true }).count(), 0)
      if (scope === 'team') await page.getByRole('tab', { name: 'Invite to workspace', exact: true }).click()
      else await page.getByLabel('Workspace', { exact: true }).selectOption('team-external')
      assert.equal(await page.getByLabel('Name (optional)', { exact: true }).getAttribute('maxlength'), '120')
      await page.getByLabel('Email', { exact: true }).fill('new@example.test')
      await page.screenshot({ path: resolve(output, `${width}-${scope}-invitation-name-limit.png`) })
      await page.getByRole('button', { name: 'Send invitation', exact: true }).last().click()
      await dialogClosed()
      const sent = (await calls(page)).find((call) => call.method === 'POST' && call.body?.email === 'new@example.test')
      assert.ok(sent)
      if (scope === 'organization') assert.equal(sent.body.teamId, 'team-external')
      await tab(page, 'Pending invitations')
      await page.getByRole('button', { name: 'Open invitation for new@example.test' }).waitFor()
      await page.getByRole('button', { name: 'Open invitation for pending@example.test' }).click()
      await page.getByRole('button', { name: 'Resend invitation', exact: true }).click()
      await dialogClosed()
      const resent = (await calls(page)).find((call) => call.path.endsWith('/invite-existing/resend'))
      assert.ok(resent)
      if (scope === 'organization') assert.equal(resent.body.teamId, 'team-external')
      await page.getByRole('button', { name: 'Open invitation for pending@example.test' }).click()
      await page.getByRole('button', { name: 'Cancel invitation', exact: true }).click()
      await page.getByText('This cannot be undone. You can send a new invitation later.').waitFor()
      await page.screenshot({ path: resolve(output, `${width}-${scope}-cancel-invitation.png`) })
      await page.getByRole('button', { name: 'Cancel invitation', exact: true }).click()
      await dialogClosed()
      assert.ok((await calls(page)).some((call) => call.path.endsWith('/invite-existing/revoke')))
    }
    await open('?scope=organization')
    await member().click()
    await page.getByLabel('Organization role', { exact: true }).selectOption('admin')
    await page.screenshot({ path: resolve(output, `${width}-organization-role-change.png`) })
    await page.getByRole('button', { name: 'Save changes', exact: true }).click()
    await dialogClosed()
    assert.ok((await calls(page)).some((call) => call.path.endsWith('/organization/members/subject-jakub/role')
      && call.body.role === 'admin'))
    await member().click()
    assert.equal(await page.getByLabel('Organization role', { exact: true }).inputValue(), 'admin')
    await page.getByRole('checkbox', { name: 'Design', exact: true }).uncheck()
    await page.getByRole('button', { name: 'Save changes', exact: true }).click()
    await dialogClosed()
    await member().click()
    assert.equal(await page.getByRole('checkbox', { name: 'Design', exact: true }).isChecked(), false)

    await open('?readOnly=1')
    await member().click()
    assert.equal(await page.getByLabel('Role', { exact: true }).isDisabled(), true)
    assert.equal(await page.getByRole('button', { name: 'Remove from team', exact: true }).count(), 0)
    await page.getByRole('button', { name: 'Cancel', exact: true }).click()
    await dialogClosed()
    assert.equal(await page.getByRole('button', { name: 'Send invitation', exact: true }).count(), 0)
    await tab(page, 'Pending invitations')
    await page.getByRole('button', { name: 'Open invitation for pending@example.test' }).click()
    assert.equal(await page.getByRole('button', { name: 'Cancel invitation', exact: true }).count(), 0)
    assert.equal(await page.getByRole('button', { name: 'Resend invitation', exact: true }).count(), 0)
    assert.equal((await calls(page)).some((call) => call.method !== 'GET'), false)

    await open('?noPermissions=1')
    assert.equal(await page.getByRole('button', { name: 'Send invitation', exact: true }).count(), 0)
    await member().click()
    assert.equal(await page.getByLabel('Role', { exact: true }).isDisabled(), true)
    assert.equal(await page.getByRole('button', { name: 'Remove from team', exact: true }).count(), 0)
    assert.equal(await page.getByRole('button', { name: 'Deactivate in organization', exact: true }).count(), 0)
    await page.getByRole('button', { name: 'Cancel', exact: true }).click()
    await tab(page, 'Pending invitations')
    await page.getByRole('button', { name: 'Open invitation for pending@example.test' }).click()
    assert.equal(await page.getByRole('button', { name: 'Resend invitation', exact: true }).count(), 0)
    assert.equal(await page.getByRole('button', { name: 'Cancel invitation', exact: true }).count(), 0)

    await open('?scope=organization&noPermissions=1')
    await member().click()
    assert.equal(await page.getByLabel('Organization role', { exact: true }).isDisabled(), true)
    assert.equal(await page.getByRole('button', { name: 'Save changes', exact: true }).isDisabled(), true)

    await open('?pendingApproval=1')
    await tab(page, 'Pending invitations')
    await page.getByRole('button', { name: 'Open invitation for pending@example.test' }).click()
    await page.getByText('Awaiting organization approval.', { exact: true }).waitFor()
    assert.equal(await page.getByRole('button', { name: 'Resend invitation', exact: true }).count(), 0)
    assert.equal(await page.getByRole('button', { name: 'Cancel invitation', exact: true }).count(), 0)
    assert.equal(await page.getByRole('button', { name: 'Approve', exact: true }).count(), 0)
    assert.equal(await page.getByRole('button', { name: 'Deny', exact: true }).count(), 0)
    assert.equal((await calls(page)).some((call) => call.method !== 'GET'), false)

    await open('?fail=role')
    await member().click()
    await page.getByLabel('Role', { exact: true }).selectOption('admin')
    await page.getByRole('button', { name: 'Save changes', exact: true }).click()
    await page.getByText('Your permission to change this role has changed. Reload members and try again.').waitFor()
    await page.screenshot({ path: resolve(output, `${width}-role-refused.png`) })
    assert.equal(await page.getByLabel('Role', { exact: true }).inputValue(), 'admin')

    await open('?slow=1')
    await member().click()
    await page.getByLabel('Role', { exact: true }).selectOption('admin')
    await page.getByRole('button', { name: 'Save changes', exact: true }).click()
    await page.getByRole('button', { name: 'Saving…', exact: true }).waitFor()
    assert.equal(await page.getByRole('button', { name: 'Saving…', exact: true }).isDisabled(), true)
    assert.equal((await calls(page)).filter((call) => call.path.endsWith('/subject-jakub/role')).length, 1)
    await dialogClosed()

    await open('?fail=invite')
    await page.getByRole('button', { name: 'Send invitation', exact: true }).click()
    await page.getByRole('tab', { name: 'Invite to workspace', exact: true }).click()
    await page.getByLabel('Email', { exact: true }).fill('draft@example.test')
    await page.getByRole('button', { name: 'Send invitation', exact: true }).last().click()
    await page.getByText('Your permission to send invitations has changed. Reload members and try again.').waitFor()
    assert.equal(await page.getByLabel('Email', { exact: true }).inputValue(), 'draft@example.test')

    await open('?scope=organization&fail=access')
    await member().click()
    await page.getByText('Team access could not be loaded.', { exact: false }).waitFor()
    assert.equal(await page.getByText('No editable team access is available.', { exact: true }).count(), 0)
    assert.equal(await page.getByRole('button', { name: 'Save changes', exact: true }).isDisabled(), true)
    await open('?fail=search')
    await page.getByRole('button', { name: 'Send invitation', exact: true }).click()
    await page.getByLabel('Search organisation members').fill('Ondřej')
    await page.getByText('Members could not be searched.', { exact: false }).waitFor()
    assert.equal(await page.getByText('No eligible members found.', { exact: true }).count(), 0)
    await page.getByRole('button', { name: 'Retry', exact: true }).click()
    assert.deepEqual(errors, [])
    console.log(`Member management ${width}px: role, activation, removal, invitations, team access, permissions and failures passed`)
    await context.close()
  }
} finally {
  await browser.close()
}
