// Spike B — what survives `UserModel.fromXlsx` → `saveToXlsx` → `fromXlsx`,
// what does not, and what the two file-path-only entry points cost a service
// that handles uploads as streams.
//
// Findings and the loss table:
// docs/plans/2026-09-15-spreadsheets-ironcalc/spike-b-xlsx.md
//
// The fixture is generated by exceljs (`test/fixtures/build-fixtures.ts`), not
// by IronCalc, so the import path is exercised against a foreign writer; an
// IronCalc-written variant is measured beside it.

import assert from 'node:assert/strict'
import { spawnSync } from 'node:child_process'
import { randomUUID } from 'node:crypto'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { after, before, describe, it } from 'node:test'

import { UserModel } from '@ironcalc/nodejs'

import {
  deriveXlsxWarnings,
  detectWorkbookFormat,
  declaredUncompressedBytes,
  readXlsxPartNames,
  scanXlsxWarnings,
} from '../src/xlsx-warnings.js'
import { buildForeignWorkbook, DATA_ROWS, SHEET } from './fixtures/build-fixtures.js'
import { assertPreserved } from './fixtures/assert-round-trip.js'
import { exportSheetCsv } from './fixtures/csv-projection.js'
import { buildStoredZip } from './fixtures/stored-zip.js'

let workspace: string
let foreignPath: string
let foreignBytes: Buffer

/** `saveToXlsx` refuses an existing path, so every write picks a fresh one. */
const scratch = (name: string): string => path.join(workspace, `${randomUUID()}-${name}`)

const measure = <T>(label: string, run: () => T): T => {
  const started = process.hrtime.bigint()
  const result = run()
  const ms = Number(process.hrtime.bigint() - started) / 1e6
  console.log(`[spike-b] ${label}: ${ms.toFixed(1)} ms`)
  return result
}

/** Import the way the import route must: read, then evaluate. */
const importXlsx = (file: string): UserModel => {
  const model = UserModel.fromXlsx(file)
  model.evaluate()
  return model
}

before(async () => {
  workspace = fs.mkdtempSync(path.join(os.tmpdir(), 'spike-b-'))
  foreignPath = path.join(workspace, 'foreign.xlsx')
  const started = process.hrtime.bigint()
  const size = await buildForeignWorkbook(foreignPath)
  const ms = Number(process.hrtime.bigint() - started) / 1e6
  console.log(`[spike-b] exceljs wrote the fixture in ${ms.toFixed(0)} ms, ${size} bytes`)
  foreignBytes = fs.readFileSync(foreignPath)
})

after(() => fs.rmSync(workspace, { recursive: true, force: true }))

describe('fromXlsx / saveToXlsx round trip', () => {
  it('imports a foreign 5-sheet, ~50 000-cell workbook and keeps contents, values, types and styles', () => {
    const first = measure('fromXlsx (foreign, ~51k cells)', () => importXlsx(foreignPath))
    const grandTotal = assertPreserved(first)

    const exported = scratch('round-1.xlsx')
    measure('saveToXlsx (foreign, ~51k cells)', () => first.saveToXlsx(exported))
    console.log(
      `[spike-b] sizes: source ${foreignBytes.length} B -> export ${fs.statSync(exported).size} B`,
    )
    const second = measure('fromXlsx (round 2)', () => importXlsx(exported))
    assert.equal(assertPreserved(second), grandTotal)

    // A third pass adds no further loss: the export is a fixed point.
    const again = scratch('round-2.xlsx')
    second.saveToXlsx(again)
    assert.deepEqual(
      readXlsxPartNames(fs.readFileSync(again)).sort(),
      readXlsxPartNames(fs.readFileSync(exported)).sort(),
    )
    assert.deepEqual(scanXlsxWarnings(fs.readFileSync(again)), [])
  })

  it('needs an explicit evaluate() after import - formulas are #ERROR! until then', () => {
    const raw = UserModel.fromXlsx(foreignPath)
    assert.equal(raw.getFormattedCellValue(SHEET.data, 2, 7), '#ERROR!')
    raw.evaluate()
    assert.equal(raw.getFormattedCellValue(SHEET.data, 2, 7), '$16.18')

    // …and an un-evaluated model exports those errors as cached values, so an
    // import that forgets `evaluate()` writes a broken version of record.
    const broken = UserModel.fromXlsx(foreignPath)
    const brokenFile = scratch('unevaluated.xlsx')
    broken.saveToXlsx(brokenFile)
    assert.equal(UserModel.fromXlsx(brokenFile).getFormattedCellValue(SHEET.data, 2, 7), '#ERROR!')
  })

  it('round-trips an IronCalc-written workbook without loss', () => {
    const source = new UserModel('native')
    source.pauseEvaluation()
    source.newSheet()
    source.renameSheet(0, 'Numbers')
    source.renameSheet(1, 'Derived')
    for (let row = 1; row <= 500; row++) {
      for (let column = 1; column <= 8; column++) {
        source.setUserInput(0, row, column, String(row * 10 + column))
      }
      source.setUserInput(1, row, 1, `=SUM(Numbers!A${row}:H${row})`)
    }
    source.updateRangeStyle(0, 1, 1, 1, 8, 'font.b', 'true')
    source.updateRangeStyle(0, 1, 1, 1, 8, 'fill.color', '#112233')
    source.updateRangeStyle(0, 2, 1, 500, 8, 'num_fmt', '#,##0.00')
    source.setFrozenRowsCount(0, 1)
    source.setFrozenColumnsCount(0, 1)
    source.setRowsHidden(0, 3, 3, true)
    source.setColumnsHidden(0, 4, 4, true)
    source.newDefinedName('Block', null, 'Numbers!$A$1:$H$500')
    source.resumeEvaluation()
    source.evaluate()

    const file = scratch('native.xlsx')
    measure('saveToXlsx (IronCalc-written, 4.5k cells)', () => source.saveToXlsx(file))
    const reloaded = measure('fromXlsx (IronCalc-written)', () => importXlsx(file))

    assert.deepEqual(
      reloaded.getWorksheetsProperties().map((s) => s.name),
      ['Numbers', 'Derived'],
    )
    assert.equal(reloaded.getCellContent(1, 7, 1), '=SUM(Numbers!A7:H7)')
    assert.equal(reloaded.getFormattedCellValue(1, 7, 1), source.getFormattedCellValue(1, 7, 1))
    assert.deepEqual(reloaded.getCellStyle(0, 1, 1), source.getCellStyle(0, 1, 1))
    assert.deepEqual(reloaded.getCellStyle(0, 2, 1), source.getCellStyle(0, 2, 1))
    assert.equal(reloaded.getFrozenRowsCount(0), 1)
    assert.equal(reloaded.getFrozenColumnsCount(0), 1)
    assert.equal(reloaded.getRowHeight(0, 3), 0)
    assert.equal(reloaded.getColumnWidth(0, 4), 0)
    assert.deepEqual(reloaded.getDefinedNameList(), source.getDefinedNameList())
    // No warnings: nothing IronCalc writes is something IronCalc drops.
    assert.deepEqual(scanXlsxWarnings(fs.readFileSync(file)), [])
  })
})

describe('the declared expansion', () => {
  it('reads the central directory, not the file size, and refuses a non-zip', () => {
    // The number an import cap has to be written against. Sheet XML expands
    // about 11:1, so the compressed size admits a file that takes the process
    // down; this comes from the central directory and inflates nothing.
    const declared = declaredUncompressedBytes(foreignBytes)
    assert.ok(declared !== null)
    assert.ok(
      declared > foreignBytes.byteLength,
      `expansion ${declared} should exceed the ${foreignBytes.byteLength}-byte package`,
    )
    // A CSV, an `.xls` and a truncated package all reach the same call, and
    // all three have to answer "not a workbook" rather than throw: the import
    // route turns `null` into a refusal a person can read.
    assert.equal(declaredUncompressedBytes(Buffer.from('a,b,c\n1,2,3\n')), null)
    assert.equal(declaredUncompressedBytes(foreignBytes.subarray(0, 64)), null)
  })
})

describe('what an import loses', () => {
  it('drops the parts and sheet features Spike B measured, and says so', () => {
    const model = importXlsx(foreignPath)
    const exported = scratch('loss.xlsx')
    model.saveToXlsx(exported)

    const sourceParts = readXlsxPartNames(foreignBytes)
    const exportedBytes = fs.readFileSync(exported)
    const exportedParts = readXlsxPartNames(exportedBytes)
    for (const gone of ['xl/media/', 'xl/drawings/', 'xl/tables/', 'xl/comments']) {
      assert.ok(sourceParts.some((p) => p.startsWith(gone)), `fixture should contain ${gone}`)
      assert.ok(!exportedParts.some((p) => p.startsWith(gone)), `${gone} should be dropped`)
    }
    assert.ok(exportedParts.includes('xl/worksheets/sheet1.xml'))

    const warnings = scanXlsxWarnings(foreignBytes)
    assert.deepEqual(
      warnings.map((w) => w.code),
      [
        'images',
        'comments',
        'tables',
        'autofilter',
        'data_validation',
        'hyperlinks',
        'sheet_protection',
        'outlines',
      ],
    )
    for (const warning of warnings) {
      assert.ok(warning.message.length > 0)
      assert.ok(warning.evidence.length > 0 && warning.evidence.length <= 8)
    }
    // The export is clean: a second import of our own file warns about nothing.
    assert.deepEqual(scanXlsxWarnings(exportedBytes), [])
    // Merges are the surprise: no binding exposes them, yet they survive.
    assert.equal(model.getCellContent(SHEET.data, 1, 9), 'MERGED BANNER')
    // A hyperlink survives only as its display text.
    assert.equal(model.getCellContent(SHEET.notes, 2, 1), 'IronCalc')
  })

  it('derives warnings from a part list alone, deterministically', () => {
    assert.deepEqual(deriveXlsxWarnings({ parts: ['xl/workbook.xml', 'xl/styles.xml'] }), [])

    const warnings = deriveXlsxWarnings({
      parts: [
        'xl/',
        '/xl/charts/chart1.xml',
        'xl/pivotTables/pivotTable1.xml',
        'xl/pivotCache/pivotCacheDefinition1.xml',
        'xl/media/image9.png',
        'xl/drawings/vmlDrawing1.vml',
        'xl/threadedComments/threadedComment1.xml',
        'xl/vbaProject.bin',
        'xl/externalLinks/externalLink1.xml',
        'xl/tables/table3.xml',
        'xl/ctrlProps/ctrlProp1.xml',
        'xl/slicers/slicer1.xml',
        'xl/embeddings/oleObject1.bin',
        'xl/connections.xml',
        'customXml/item1.xml',
      ],
    })
    assert.deepEqual(warnings.map((w) => w.code), [
      'charts',
      'pivot_tables',
      'images',
      'comments',
      'macros',
      'external_links',
      'tables',
      'form_controls',
      'slicers',
      'embedded_objects',
      'data_connections',
      'custom_xml',
    ])
    // Directory entries are ignored; a leading slash is tolerated.
    assert.deepEqual(warnings[0]?.evidence, ['xl/charts/chart1.xml'])
    // A `.vml` legacy drawing is a comment's shape, not an image.
    const images = warnings.find((w) => w.code === 'images')
    assert.deepEqual(images?.evidence, ['xl/media/image9.png'])
  })

  it('does not warn about the markup Excel writes on every sheet', () => {
    const inert = `<worksheet><sheetPr/><pageSetup orientation="portrait"/>
      <headerFooter/><row r="1" outlineLevel="0"/><hyperlinks/></worksheet>`
    assert.deepEqual(
      deriveXlsxWarnings({ parts: [], sheets: [['xl/worksheets/sheet1.xml', inert]] }),
      [],
    )
    const real = `<worksheet><autoFilter ref="A1:C1"/><dataValidation sqref="A2"/>
      <hyperlink ref="B2" r:id="rId1"/><sheetProtection sheet="1"/>
      <row r="4" outlineLevel="2"/><x14:sparklineGroup/></worksheet>`
    assert.deepEqual(
      deriveXlsxWarnings({ parts: [], sheets: [['xl/worksheets/sheet1.xml', real]] }).map(
        (w) => w.code,
      ),
      ['autofilter', 'data_validation', 'hyperlinks', 'sheet_protection', 'outlines', 'sparklines'],
    )
  })

  it('caps the evidence it stores', () => {
    const parts = Array.from({ length: 40 }, (_, i) => `xl/charts/chart${i}.xml`)
    const [warning] = deriveXlsxWarnings({ parts })
    assert.equal(warning?.evidence.length, 8)
  })
})

describe('the temp-file dance the file-path-only API forces', () => {
  // `UserModel.fromXlsx(filePath)` and `saveToXlsx(filePath)` take paths, not
  // buffers, and 0.8.3 has no buffer variant. FileService hands us a stream or
  // a Buffer, so every import and export goes through a private temp file.
  // These are the rules that dance has to follow.

  it('refuses to overwrite an existing file, so every write needs a fresh path', () => {
    const model = new UserModel('overwrite')
    model.setUserInput(0, 1, 1, '1')
    const file = scratch('once.xlsx')
    model.saveToXlsx(file)
    assert.throws(() => model.saveToXlsx(file), /already exists/)
  })

  it('writes exactly the path given, with no extension of its own', () => {
    const model = new UserModel('noext')
    model.setUserInput(0, 1, 1, '1')
    const file = scratch('no-extension')
    model.saveToXlsx(file)
    assert.ok(fs.existsSync(file))
    assert.ok(!fs.existsSync(`${file}.xlsx`))
  })

  it('ABORTS THE PROCESS when the parent directory is missing', () => {
    // xlsx/src/export/mod.rs unwraps the file handle: this is a Rust panic in
    // a napi callback, not a JS throw, and it takes the whole replica with it.
    // Proven in a child process so this suite survives it.
    const target = path.join(workspace, 'no-such-dir', 'a.xlsx')
    const script = `
      const { UserModel } = require('@ironcalc/nodejs')
      const m = new UserModel('x'); m.setUserInput(0, 1, 1, '1')
      try { m.saveToXlsx(${JSON.stringify(target)}) } catch { console.log('CAUGHT') }
      console.log('SURVIVED')
    `
    const run = spawnSync(process.execPath, ['-e', script], { encoding: 'utf8' })
    assert.ok(!run.stdout.includes('SURVIVED'), 'saveToXlsx into a missing directory is not catchable')
    assert.notEqual(run.status, 0)
    assert.match(run.stderr, /panicked at|fatal runtime error/)
  })

  it('is safe for concurrent exports as long as each picks its own path', async () => {
    const directory = path.join(workspace, 'concurrent')
    fs.mkdirSync(directory, { recursive: true })
    const started = process.hrtime.bigint()
    const files = await Promise.all(
      Array.from({ length: 24 }, async (_, i) => {
        const model = new UserModel(`c${i}`)
        model.setUserInput(0, 1, 1, String(i))
        const file = path.join(directory, `${randomUUID()}.xlsx`)
        model.saveToXlsx(file)
        return file
      }),
    )
    const ms = Number(process.hrtime.bigint() - started) / 1e6
    console.log(`[spike-b] 24 concurrent saveToXlsx: ${ms.toFixed(0)} ms`)
    assert.equal(new Set(files).size, 24)
    assert.ok(files.every((f) => fs.statSync(f).size > 0))
    // Cleanup is ours: the binding never removes anything it wrote.
    fs.rmSync(directory, { recursive: true, force: true })
    assert.ok(!fs.existsSync(directory))
  })

  it('survives the buffer -> temp file -> model -> temp file -> buffer cycle', () => {
    // The exact shape Phase 2's `importSpreadsheet` / `exportSpreadsheet`
    // should use: one private directory per call, fresh names, finally-removed.
    const withTempDirectory = <T>(run: (dir: string) => T): T => {
      const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'nessie-xlsx-'))
      try {
        return run(dir)
      } finally {
        fs.rmSync(dir, { recursive: true, force: true })
      }
    }
    const before = fs.readdirSync(os.tmpdir()).filter((n) => n.startsWith('nessie-xlsx-')).length
    const roundTripped = withTempDirectory((dir) => {
      const input = path.join(dir, `${randomUUID()}.xlsx`)
      fs.writeFileSync(input, foreignBytes, { mode: 0o600 })
      const model = importXlsx(input)
      const output = path.join(dir, `${randomUUID()}.xlsx`)
      model.saveToXlsx(output)
      return fs.readFileSync(output)
    })
    assert.ok(roundTripped.length > 0)
    assert.equal(detectWorkbookFormat(roundTripped), 'xlsx')
    assert.equal(
      fs.readdirSync(os.tmpdir()).filter((n) => n.startsWith('nessie-xlsx-')).length,
      before,
    )
  })
})

describe('bad and hostile uploads', () => {
  const write = (name: string, bytes: Buffer): string => {
    const file = scratch(name)
    fs.writeFileSync(file, bytes)
    return file
  }

  it('rejects a legacy .xls cleanly, and the sniffer names it before the engine sees it', () => {
    const ole2 = Buffer.concat([
      Buffer.from([0xd0, 0xcf, 0x11, 0xe0, 0xa1, 0xb1, 0x1a, 0xe1]),
      Buffer.alloc(4096),
    ])
    assert.equal(detectWorkbookFormat(ole2), 'xls')
    // Renaming it .xlsx changes nothing: the magic still says .xls.
    assert.equal(detectWorkbookFormat(ole2.subarray(0, 512)), 'xls')
    assert.throws(() => UserModel.fromXlsx(write('legacy.xls', ole2)), /Zip Error/)
  })

  it('throws, not aborts, on corrupt, empty, truncated and non-workbook zips', () => {
    const model = new UserModel('good')
    model.setUserInput(0, 1, 1, '1')
    const good = scratch('good.xlsx')
    model.saveToXlsx(good)
    const goodBytes = fs.readFileSync(good)

    const cases: Array<[string, Buffer]> = [
      ['empty', Buffer.alloc(0)],
      ['junk', Buffer.from('not a zip at all, really')],
      ['truncated', goodBytes.subarray(0, Math.floor(goodBytes.length / 2))],
      ['csv-renamed', Buffer.from('a,b\n1,2\n')],
    ]
    for (const [name, bytes] of cases) {
      assert.throws(() => UserModel.fromXlsx(write(`${name}.xlsx`, bytes)), /Zip Error/, name)
    }
    assert.throws(() => UserModel.fromXlsx(path.join(workspace, 'absent.xlsx')), /I\/O Error/)

    // The sniffer separates the cases the engine's one message cannot.
    assert.equal(detectWorkbookFormat(Buffer.alloc(0)), 'unknown')
    assert.equal(detectWorkbookFormat(Buffer.from('a,b\n1,2\n')), 'csv-or-text')
    assert.equal(detectWorkbookFormat(goodBytes.subarray(0, 512)), 'xlsx')
    assert.throws(() => readXlsxPartNames(Buffer.from('nope')), /XLSX_NOT_A_ZIP/)
  })

  it('rejects a well-formed zip that is not a workbook without reading it all', () => {
    const entries = Array.from({ length: 2000 }, (_, i) => [`f${i}.txt`, Buffer.from('x')] as const)
    const zip = buildStoredZip(entries)
    const file = write('not-a-workbook.xlsx', zip)
    const started = process.hrtime.bigint()
    assert.throws(() => UserModel.fromXlsx(file), /Zip Error/)
    const ms = Number(process.hrtime.bigint() - started) / 1e6
    console.log(`[spike-b] rejecting a 2 000-entry non-workbook zip: ${ms.toFixed(1)} ms`)
    assert.ok(ms < 2000, 'rejection must not depend on entry count')
    assert.equal(readXlsxPartNames(zip).length, 2000)
    assert.deepEqual(scanXlsxWarnings(zip), [])
  })
})

describe('CSV', () => {
  it('pasteCsvString is TAB-separated, not comma-separated', () => {
    const tabs = new UserModel('tsv')
    tabs.pasteCsvString(0, 1, 1, 2, 3, 'a\tb\tc\n1\t2\t3\n')
    assert.equal(tabs.getCellContent(0, 1, 3), 'c')
    assert.equal(tabs.getCellContent(0, 2, 1), '1')

    const commas = new UserModel('csv')
    commas.pasteCsvString(0, 1, 1, 2, 3, 'a,b,c\n1,2,3\n')
    assert.equal(commas.getCellContent(0, 1, 1), 'a,b,c') // one cell, not three
    assert.equal(commas.getCellContent(0, 1, 2), '')
  })

  it('ignores the area extent and needs the selection at a corner', () => {
    // The area is an anchor, not a clamp: a 1x1 area still takes the whole
    // 2x3 block. An importer cannot bound a paste by passing a small area —
    // it has to size the text itself.
    const anchorOnly = new UserModel('clamp')
    anchorOnly.pasteCsvString(0, 1, 1, 1, 1, 'a\tb\tc\n1\t2\t3\n')
    assert.equal(anchorOnly.getCellContent(0, 1, 3), 'c')
    assert.equal(anchorOnly.getCellContent(0, 2, 3), '3')
    assert.deepEqual(anchorOnly.getSheetDimensions(0), [1, 2, 1, 3])

    const anchored = new UserModel('anchor')
    assert.throws(
      () => anchored.pasteCsvString(0, 5, 3, 6, 4, 'a\tb\nc\td\n'),
      /not in one of the corners/,
    )
    anchored.setSelectedCell(5, 3)
    anchored.pasteCsvString(0, 5, 3, 6, 4, 'a\tb\nc\td\n')
    assert.equal(anchored.getCellContent(0, 6, 4), 'd')
  })

  it('coerces types, keeps formulas and handles CRLF and quotes', () => {
    const model = new UserModel('types')
    model.pasteCsvString(0, 1, 1, 2, 5, '1\t1.5\t2024-01-02\ttrue\t 007\r\n=1+1\t"a\tb"\t\t\t\r\n')
    model.evaluate()
    assert.deepEqual([1, 2, 3, 4, 5].map((c) => model.getCellType(0, 1, c)), [1, 1, 1, 4, 1])
    assert.equal(model.getFormattedCellValue(0, 1, 4), 'TRUE')
    assert.equal(model.getFormattedCellValue(0, 1, 5), '7')
    assert.equal(model.getCellContent(0, 2, 1), '=1+1')
    assert.equal(model.getFormattedCellValue(0, 2, 1), '2')
    assert.equal(model.getCellContent(0, 2, 2), 'a\tb') // quoted tab kept
  })

  it('imports 50 000 cells under one pause/resume and leaves diffs to flush', () => {
    const rows = 5000
    const columns = 10
    const text = Array.from({ length: rows }, (_, r) =>
      Array.from({ length: columns }, (_, c) => String(r * columns + c)).join('\t'),
    ).join('\n')
    const model = new UserModel('bulk-csv')
    model.pauseEvaluation()
    measure('pasteCsvString (50 000 cells)', () =>
      model.pasteCsvString(0, 1, 1, rows, columns, text),
    )
    model.resumeEvaluation()
    model.evaluate()
    assert.deepEqual(model.getSheetDimensions(0), [1, rows, 1, columns])
    assert.equal(model.getCellContent(0, rows, columns), String(rows * columns - 1))
    const diffs = model.flushSendQueue()
    console.log(`[spike-b] 50 000-cell paste flushed ${diffs.length} diff bytes`)
    assert.ok(diffs.length > 10_000)
    // A drained queue is one byte (`[0]`, the empty list), never zero bytes.
    assert.deepEqual([...model.flushSendQueue()], [0])
  })

  it('exports formatted values as RFC 4180 CSV', () => {
    const model = importXlsx(foreignPath)
    const started = process.hrtime.bigint()
    const csv = exportSheetCsv(model, SHEET.data)
    const ms = Number(process.hrtime.bigint() - started) / 1e6
    console.log(
      `[spike-b] CSV export of ${DATA_ROWS + 1} rows: ${ms.toFixed(0)} ms, ${csv.length} chars`,
    )
    const lines = csv.split('\n')
    assert.equal(lines.length, DATA_ROWS + 1)
    assert.equal(lines[0], 'Id,Name,Region,Date,Amount,Tax,Total,,MERGED BANNER,,')
    // Formatted, not raw: the date and currency formats come through.
    assert.ok(lines[1]?.includes('2024-02-02'))
    assert.ok(lines[1]?.includes('$16.18'))
    assert.ok((lines[1]?.split(',').length ?? 0) >= 7)
  })
})
