// HTTP client + shared API types.
export {
  createApiClient,
  type ApiClient,
  type ApiClientConfig,
} from './api-client.js'

// Shared API data-shape types (also re-exported via api-client for back-compat).
export type {
  AgentRecord,
  AgentTriggerDeliveryRecord,
  AgentTriggerRecord,
  AuthProviderDescriptor,
  BootstrapModeResponse,
  CallParticipantRecord,
  CallRecord,
  ChannelMetadataRecord,
  ChannelRecord,
  FavoriteRecord,
  FavoriteTargetType,
  MessageReaction,
  MessageSearchResult,
  PresenceEntry,
  PresenceListResponse,
  PresenceManualState,
  PresenceState,
  PersonalAssistantBootstrapResponse,
  PersonalAssistantConfigSummary,
  PersonalAssistantInstanceRecord,
  PersonalAssistantStateResponse,
  ProjectMemberRecord,
  ProjectRecord,
  SessionState,
  TeamRecord,
  ThreadMessageRecord,
  ThreadRecord,
  ToolDescriptor,
  UserActiveStatus,
  UserRecord,
  UserStatusRecord,
  UserStatusRuleRecord,
  UserStatusRuleScope,
  UserStatusScheduleKind,
  UserStatusScheduleRecord,
  WorkflowInstallationRecord,
  WorkflowRunDetail,
  WorkflowRunRecord,
  WorkflowRunStatus,
  WorkflowStepRunRecord,
  WorkflowStepRunStatus,
  WorkflowStepSamplesRecord,
  WorkflowTemplateRecord,
} from './api-types.js'

// Schema-sourced types previously surfaced from the admin api-client module.
export type {
  AgentModelOption,
  AgentActivityResponse,
  AgentChild,
  AgentMessage,
  AgentStatusResponse,
  BuildMeProjectHandoffIntent,
  BuildMeProjectHandoffRequest,
  CommsConnectionDetail,
  CommsConnectionListResponse,
  CommsConnectionStartResponse,
  CommsConnectionStatus,
  CommsConnectionSummary,
  CommsProvider,
  CommsResourceRecord,
  CommsResourcesPatchRequest,
  CommsResourceToggle,
  CommsSyncJobRecord,
  CommsSyncPhase,
  CommsSyncStatus,
  CreateFeedbackRequest,
  DeepTestReviewDepth,
  DeepTestReviewHandoffRequest,
  DeepSignalSignalAction,
  DeepSignalSignalActRequest,
  DeepSignalSignalActResponse,
  DeepSignalSignalKind,
  DeepSignalSignalRecord,
  DeepSignalSignalStatus,
  DeepSignalSignalsResponse,
  DeepWaterResearchDepth,
  DeepWaterAgentAccessResponse,
  DeepWaterAgentAccessTarget,
  DeepWaterResearchLauncherPreset,
  DeepWaterResearchLaunchRequest,
  DeepWaterResearchRunRecord,
  ExecutorAccessChangeRequest,
  ExecutorAccessChangeResponse,
  ExecutorAccessViewResponse,
  ExecutorCreateResponse,
  ExecutorPairingInvitationResponse,
  ExecutorRecordResponse,
  PendingExecutorEnrollmentResponse,
  PreparedExecutorAccessChangeResponse,
  FeedbackRecord,
  IntegratedProductAuthMode,
  IntegratedProductCategory,
  IntegratedProductHealthStatus,
  IntegratedProductInstallState,
  IntegratedProductResponse,
  IntegrationPluginAvailability,
  IntegrationPluginInstallMode,
  IntegrationPluginManifest,
  IntegrationPluginPrivacyTier,
  IntegrationPluginSurfaceStatus,
  IntegrationUiCard,
  IntegrationUiCardAction,
  IntegrationUiCardField,
  IntegrationUiCardStatus,
  MeResponse,
  OrganizationSummary,
  ProductAccountLinkRecord,
  ProductAccountLinkStatus,
  ProductIntegrationRunStatus,
  ProductMcpInstallationRecord,
  ProductTeamEnablementAuthority,
  ProductTeamEnablementRecord,
  SetProductTeamEnablementRequest,
  SetDeepWaterAgentAccessRequest,
  ToolCallEntry,
  UpdateOrganizationLogoRequest,
} from '@nessie/schemas'

// React context + hook for the API client.
export {
  ApiClientProvider,
  useApiClient,
  type ApiClientProviderProps,
} from './ApiClientProvider.js'

// TanStack Query provider + client factory.
export {
  createQueryClient,
  QueryProvider,
  type QueryProviderProps,
} from './QueryProvider.js'

// PKCE / external-auth helpers (framework-neutral; storage + base URL injected).
export {
  beginExternalAuth,
  clearPendingExternalAuth,
  readPendingExternalAuth,
  type BeginExternalAuthInput,
  type PendingExternalAuth,
  type PkceStorage,
} from './pkce.js'

// Framework-neutral auth/session flows (token exchange, session shape).
export {
  AuthSessionApiError,
  createAccessTokenRefreshCoordinator,
  createAuthSessionApi,
  createSessionMutationCoordinator,
  getAccessTokenExpiresAtMs,
  getAccessTokenRenewalDelayMs,
  type AccessTokenRefreshCoordinator,
  type AuthSessionApi,
  type AuthSessionState,
  type BootstrapInput,
  type LoginInput,
  type SessionPayload,
  type SessionMutationCoordinator,
  type SessionSnapshot,
  type SwitchContextInput,
  type SwitchUoaWorkspaceInput,
  type TokenStore,
} from './auth-session.js'
