import type { Surface } from './page-types'
import {
  toAdmin,
  toConnections,
  toOrganizationPairedAgents,
  toPairedAgents,
  toAgents,
  toApps,
  toExecutors,
  toStatuses,
  toTools,
  toTriggers,
  toWorkflows,
} from './surface-parents'

export const createAdminSurfaces = (adminRoot: string): Surface[] => [
  {
    contextualList: true,
    depth: 0,
    pattern: /^\/settings$/,
    root: adminRoot,
    section: 'admin',
    type: 'root',
  },
  {
    depth: 2,
    identityOf: (match) => `status:${match[1]}`,
    keyScope: () => 'status',
    parentOf: toStatuses,
    // Not `splitInline`: a status is its own route component now, so a wide
    // layout pushes it like every other detail screen rather than the list
    // page rendering it in a second column of its own.
    pattern: /^\/settings\/statuses\/([^/]+)$/,
    root: adminRoot,
    section: 'admin',
    type: 'nested',
  },
  {
    // One connected account, pushed from the Email or Slack tab.
    depth: 2,
    identityOf: (match) => `connection:${match[1]}`,
    keyScope: () => 'connection',
    parentOf: toConnections,
    pattern: /^\/settings\/connections\/([^/]+)$/,
    root: adminRoot,
    section: 'admin',
    type: 'detail',
  },
  {
    // One paired agent, pushed from either paired-agent list. Declared ahead of
    // the generic `/settings/:tab` row, which would otherwise swallow them.
    depth: 2,
    identityOf: (match) => `paired-agent:${match[1]}`,
    keyScope: () => 'paired-agent',
    parentOf: toOrganizationPairedAgents,
    pattern: /^\/settings\/organization\/paired-agents\/([^/]+)$/,
    root: adminRoot,
    section: 'admin',
    type: 'detail',
  },
  {
    depth: 2,
    identityOf: (match) => `paired-agent:${match[1]}`,
    keyScope: () => 'paired-agent',
    parentOf: toPairedAgents,
    pattern: /^\/settings\/paired-agents\/([^/]+)$/,
    root: adminRoot,
    section: 'admin',
    type: 'detail',
  },
  {
    // Every settings page shares one screen identity, so page A → page B swaps
    // in place exactly as it does today.
    depth: 1,
    intent: { state: ['tab', 'membersTab', 'automaticMembershipRule'] },
    parentOf: toAdmin,
    pattern: /^\/settings\/([^/]+)$/,
    root: adminRoot,
    section: 'admin',
    type: 'detail',
  },
  {
    // The team roster, the team/organisation Secrets pages, the organisation's
    // paired-agent governance view and its model catalogue are direct sibling
    // doorways of their organisation counterparts, not tabs nested inside
    // `/settings/team` or `/settings/organization`.
    depth: 1,
    intent: { state: ['tab'] },
    parentOf: toAdmin,
    pattern: /^\/settings\/(?:team\/(?:members|models|secrets)|organization\/(?:models|paired-agents|secrets))$/,
    root: adminRoot,
    section: 'admin',
    type: 'detail',
  },
  {
    depth: 1,
    intent: { state: ['scope'] },
    parentOf: toAdmin,
    pattern: /^\/agents$/,
    root: adminRoot,
    section: 'admin',
    type: 'detail',
  },
  {
    depth: 2,
    identityOf: (match) => `designer:${match[1] ?? 'new'}`,
    keyScope: () => 'agent-designer',
    intent: { state: ['designerSection', 'parentId'] },
    parentOf: toAgents,
    pattern: /^\/agents\/designer(?:\/([^/]+))?$/,
    root: adminRoot,
    section: 'admin',
    type: 'flow',
  },
  {
    depth: 2,
    identityOf: (match) => `workflow-designer:${match[1] ?? 'new'}`,
    keyScope: () => 'workflow-designer',
    parentOf: toWorkflows,
    pattern: /^\/agents\/workflow-designer(?:\/([^/]+))?$/,
    root: adminRoot,
    section: 'admin',
    type: 'flow',
  },
  {
    depth: 1,
    parentOf: toAdmin,
    pattern: /^\/agents\/task-sets$/,
    root: adminRoot,
    section: 'admin',
    type: 'detail',
  },
  {
    depth: 2,
    identityOf: () => 'task-set:new',
    intent: { state: ['sourcePageId', 'sourceVersionId', 'format'] },
    keyScope: () => 'task-set-create',
    parentOf: () => ({ label: 'Task Sets', pathname: '/agents/task-sets' }),
    pattern: /^\/agents\/task-sets\/new$/,
    root: adminRoot,
    section: 'admin',
    type: 'flow',
  },
  {
    depth: 2,
    identityOf: (match) => `task-set:${match[1]}`,
    intent: { state: ['item'] },
    keyScope: () => 'task-set',
    parentOf: () => ({ label: 'Task Sets', pathname: '/agents/task-sets' }),
    pattern: /^\/agents\/task-sets\/(?!new$)([^/]+)$/,
    root: adminRoot,
    section: 'admin',
    type: 'detail',
  },
  {
    // The automation browsers' column stages are state, not routes.
    depth: 1,
    intent: {
      consume: ['create', 'scopeProjectId'],
      hash: ['confirmationToken'],
      state: [
        'accessChange', 'promotion', 'tab',
        'status', 'search', 'type', 'source', 'instance', 'deepWaterInstance',
      ],
    },
    parentOf: toAdmin,
    pattern: /^\/agents\/(?:workflows|triggers|tools|executors)$/,
    root: adminRoot,
    section: 'admin',
    type: 'detail',
  },
  {
    // One paired machine, pushed from the Executors table. Its tab and any
    // prepared change it is showing are state, not history.
    depth: 2,
    identityOf: (match) => `executor:${match[1]}`,
    intent: { state: ['tab'] },
    keyScope: () => 'executor',
    parentOf: toExecutors,
    pattern: /^\/agents\/executors\/([^/]+)$/,
    root: adminRoot,
    section: 'admin',
    type: 'detail',
  },
  {
    depth: 3,
    identityOf: (match) => `executor-session:${match[1]}:${match[2]}`,
    keyScope: () => 'executor-session',
    parentOf: () => ({ label: 'Sessions', pathname: '/agents/executor-sessions' }),
    pattern: /^\/agents\/executors\/([^/]+)\/sessions\/([^/]+)$/,
    root: adminRoot,
    section: 'admin',
    type: 'detail',
  },
  {
    depth: 2, identityOf: () => 'executor-sessions', keyScope: () => 'executor-sessions',
    parentOf: toExecutors, pattern: /^\/agents\/executor-sessions$/, root: adminRoot,
    section: 'admin', type: 'detail',
  },
  {
    // One tool, pushed from the Tools table.
    depth: 2,
    identityOf: (match) => `tool:${match[1]}`,
    keyScope: () => 'tool',
    parentOf: toTools,
    pattern: /^\/agents\/tools\/([^/]+)$/,
    root: adminRoot,
    section: 'admin',
    type: 'detail',
  },
  {
    // One trigger, pushed from the Triggers table.
    depth: 2,
    identityOf: (match) => `trigger:${match[1]}`,
    keyScope: () => 'trigger',
    parentOf: toTriggers,
    pattern: /^\/agents\/triggers\/([^/]+)$/,
    root: adminRoot,
    section: 'admin',
    type: 'detail',
  },
  {
    // Depth 3 under the agent: Back lands on the owner of this mailbox, and a
    // conversation query survives a reload.
    depth: 3,
    identityOf: (match) => `agent-mailbox:${match[1]}`,
    intent: { state: ['conversation', 'mailboxFilter'] },
    keyScope: () => 'agent-mailbox',
    parentOf: (match) => ({
      label: 'Back to agent',
      pathname: `/agents/${match[1]}`,
    }),
    pattern: /^\/agents\/([^/]+)\/mailbox$/,
    root: adminRoot,
    section: 'admin',
    type: 'nested',
  },
  {
    // Dynamic agent id last, mirroring the router's own ranking.
    depth: 2,
    identityOf: (match) => `agent:${match[1]}`,
    keyScope: () => 'agent',
    intent: { state: ['agentTab'] },
    parentOf: toAgents,
    pattern: /^\/agents\/(?!(?:task-sets|executor-sessions)$)([^/]+)$/,
    root: adminRoot,
    section: 'admin',
    type: 'detail',
  },
  {
    depth: 1,
    intent: { state: ['filter'] },
    parentOf: toAdmin,
    pattern: /^\/apps$/,
    root: adminRoot,
    section: 'admin',
    type: 'detail',
  },
  {
    depth: 2,
    identityOf: (match) => `app:${match[1]}`,
    keyScope: () => 'app',
    intent: { consume: ['connect'], state: ['tab'] },
    parentOf: toApps,
    pattern: /^\/apps\/([^/]+)$/,
    root: adminRoot,
    section: 'admin',
    type: 'nested',
  },
  {
    // Governance and billing pages sit beside settings, one step in from Admin.
    depth: 1,
    intent: { consume: ['uoa_billing'] },
    parentOf: toAdmin,
    pattern: /^\/(?:audit|tokens|policy)$/,
    root: adminRoot,
    section: 'admin',
    type: 'detail',
  },
  {
    // Reached from any section, so Back returns to the reader's origin and
    // falls back to Admin on a cold deep link.
    depth: 1,
    parent: 'origin',
    parentOf: toAdmin,
    pattern: /^\/(?:alerts|feedback)$/,
    root: adminRoot,
    section: 'admin',
    type: 'detail',
  },
  {
    depth: 1,
    parentOf: toAdmin,
    pattern: /^\/ops$/,
    root: adminRoot,
    section: 'admin',
    type: 'detail',
  },
  {
    // `/ops` is super-admin-only; this owner-only page never falls back there.
    depth: 2,
    parent: 'origin',
    parentOf: toAdmin,
    pattern: /^\/ops\/usage$/,
    root: adminRoot,
    section: 'admin',
    type: 'nested',
  },
]
