export {
  buildNativeSourceRef,
  buildSpaceSourceRef,
  createNativeKnowledgeProvider,
} from './native-provider.js'
export type {
  CreatePageInput,
  CreateSpaceInput,
  KnowledgeAuthorType,
  KnowledgePageRecord,
  KnowledgePageStatus,
  KnowledgePageTreeNode,
  KnowledgePageVersionRecord,
  KnowledgeProvider,
  KnowledgeProviderCapabilities,
  KnowledgeProviderKind,
  KnowledgeScopeInput,
  KnowledgeSearchHit,
  KnowledgeSensitivityTier,
  KnowledgeSpaceRecord,
  KnowledgeVisibility,
  ListPagesInput,
  ListSpacesInput,
  MovePageInput,
  PublishPageInput,
  RestorePageVersionInput,
  SearchPagesInput,
  UpdatePageInput,
  UpdateSpaceInput,
} from './types.js'
